% -------------------------------------------------------------------
%  Generated by MATLAB on 23-Jan-2024 13:01:29
%  MATLAB version: 9.12.0.1884302 (R2022a)
% -------------------------------------------------------------------
saveVarsMat = load('tfident1p.mat');

tf2 = saveVarsMat.tf2; % <1x1 idtf> unsupported class

clear saveVarsMat;
