% -------------------------------------------------------------------
%  Generated by MATLAB on 23-Jan-2024 12:57:17
%  MATLAB version: 9.12.0.1884302 (R2022a)
% -------------------------------------------------------------------
saveVarsMat = load('tfident.mat');

tf1 = saveVarsMat.tf1; % <1x1 idtf> unsupported class

clear saveVarsMat;
