% -------------------------------------------------------------------
%  Generated by MATLAB on 23-Jan-2024 13:39:08
%  MATLAB version: 9.12.0.1884302 (R2022a)
% -------------------------------------------------------------------
saveVarsMat = load('tfident502p.mat');

tf3 = saveVarsMat.tf3; % <1x1 idtf> unsupported class

clear saveVarsMat;
