% -------------------------------------------------------------------
%  Generated by MATLAB on 23-Jan-2024 13:40:36
%  MATLAB version: 9.12.0.1884302 (R2022a)
% -------------------------------------------------------------------
saveVarsMat = load('tfident501p.mat');

tf4 = saveVarsMat.tf4; % <1x1 idtf> unsupported class

clear saveVarsMat;
